#!/bin/sh

echo "\033[1;33m:: \033[0mStarted getting data from channel \033[1;33m$1\033[0m..."
VIDS="$(curl -Lsf "https://opentube.kocotian.pl/api/getChannelVideos.php?id=$1")"
VIDCOUNT="$(echo "$VIDS" | wc -l)"
echo "\033[1;32m:: \033[0mDone"

help()
{
	echo "help:
	h = this help
	q = quit
	l = list videos
	p = play video
	d = download video"
}

list()
{
	LIST="channel have \033[1;33m$VIDCOUNT \033[0mvideos"; NUMBER=1
	echo "$VIDS" | while read LINE
	do
		LIST="$LIST\n\033[1;33m$NUMBER. \033[1;97m${LINE##*	}"
		[ "$NUMBER" = "$VIDCOUNT" ] && (echo "$LIST" | less)
		NUMBER=$(($NUMBER + 1))
	done
}

play()
{
	echo -n "\033[1;34m:: \033[0mgive video number (h for help) \033[1;34m>> \033[0m"
	read VIDNO
	[ "$VIDNO" = "q" ] && return
	[ "$VIDNO" = "l" ] && list && play && return
	[ "$VIDNO" = "h" ] && help && play && return
	VID=$(echo "$VIDS" | sed -n ${VIDNO}p)
	echo "\033[1;32m:: \033[0mplaying \033[1;33m${VID##*	}\033[0m..."
	mpv "https://youtu.be/${VID%%	*}"
}

download()
{
	echo -n "\033[1;34m:: \033[0mgive video number (h for help) \033[1;34m>> \033[0m"
	read VIDNO
	[ "$VIDNO" = "q" ] && return
	[ "$VIDNO" = "l" ] && list && download && return
	[ "$VIDNO" = "h" ] && help && download && return
	VID=$(echo "$VIDS" | sed -n ${VIDNO}p)
	echo "\033[1;32m:: \033[0mdownloading \033[1;33m${VID##*	}\033[0m..."
	youtube-dl --add-metadata -i "https://youtu.be/${VID%%	*}"
}

while true
do
	echo -n "\033[1;34m:: \033[0mwhat to do? (h for help) \033[1;34m>> \033[0m"
	read WHAT
	[ "$WHAT" = "q" ] && break
	[ "$WHAT" = "h" ] && help
	[ "$WHAT" = "l" ] && list
	[ "$WHAT" = "p" ] && play
	[ "$WHAT" = "d" ] && download
done
